# Generated by Django 5.2.4 on 2025-07-28 15:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExchangeProposal",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("comment", models.TextField(verbose_name="Комментарий к сделки")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания сделки"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("1", "ожидает"),
                            ("2", "принята"),
                            ("3", "отклонена"),
                        ],
                        max_length=300,
                        verbose_name="Статус сделки",
                    ),
                ),
            ],
        ),
    ]
