# Generated by Django 5.2.4 on 2025-07-28 22:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goods", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=200, null=True, unique=True, verbose_name="URL"
            ),
        ),
    ]
